---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuadrant-system
resources:
- github.com/Kuadrant/limitador-operator/config/default?ref=main
patchesStrategicMerge:
- delete-ns.yaml
