// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `envoy/type/matcher/v3/metadata.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataMatcher {
    // message fields
    pub filter: ::std::string::String,
    pub path: ::protobuf::RepeatedField<MetadataMatcher_PathSegment>,
    pub value: ::protobuf::SingularPtrField<super::value::ValueMatcher>,
    pub invert: bool,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataMatcher {
    fn default() -> &'a MetadataMatcher {
        <MetadataMatcher as ::protobuf::Message>::default_instance()
    }
}

impl MetadataMatcher {
    pub fn new() -> MetadataMatcher {
        ::std::default::Default::default()
    }

    // string filter = 1;


    pub fn get_filter(&self) -> &str {
        &self.filter
    }
    pub fn clear_filter(&mut self) {
        self.filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_filter(&mut self, v: ::std::string::String) {
        self.filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter(&mut self) -> &mut ::std::string::String {
        &mut self.filter
    }

    // Take field
    pub fn take_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filter, ::std::string::String::new())
    }

    // repeated .envoy.type.matcher.v3.MetadataMatcher.PathSegment path = 2;


    pub fn get_path(&self) -> &[MetadataMatcher_PathSegment] {
        &self.path
    }
    pub fn clear_path(&mut self) {
        self.path.clear();
    }

    // Param is passed by value, moved
    pub fn set_path(&mut self, v: ::protobuf::RepeatedField<MetadataMatcher_PathSegment>) {
        self.path = v;
    }

    // Mutable pointer to the field.
    pub fn mut_path(&mut self) -> &mut ::protobuf::RepeatedField<MetadataMatcher_PathSegment> {
        &mut self.path
    }

    // Take field
    pub fn take_path(&mut self) -> ::protobuf::RepeatedField<MetadataMatcher_PathSegment> {
        ::std::mem::replace(&mut self.path, ::protobuf::RepeatedField::new())
    }

    // .envoy.type.matcher.v3.ValueMatcher value = 3;


    pub fn get_value(&self) -> &super::value::ValueMatcher {
        self.value.as_ref().unwrap_or_else(|| <super::value::ValueMatcher as ::protobuf::Message>::default_instance())
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    pub fn has_value(&self) -> bool {
        self.value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: super::value::ValueMatcher) {
        self.value = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut super::value::ValueMatcher {
        if self.value.is_none() {
            self.value.set_default();
        }
        self.value.as_mut().unwrap()
    }

    // Take field
    pub fn take_value(&mut self) -> super::value::ValueMatcher {
        self.value.take().unwrap_or_else(|| super::value::ValueMatcher::new())
    }

    // bool invert = 4;


    pub fn get_invert(&self) -> bool {
        self.invert
    }
    pub fn clear_invert(&mut self) {
        self.invert = false;
    }

    // Param is passed by value, moved
    pub fn set_invert(&mut self, v: bool) {
        self.invert = v;
    }
}

impl ::protobuf::Message for MetadataMatcher {
    fn is_initialized(&self) -> bool {
        for v in &self.path {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.value {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filter)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.path)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.value)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.invert = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filter.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filter);
        }
        for value in &self.path {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let Some(ref v) = self.value.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.invert != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filter.is_empty() {
            os.write_string(1, &self.filter)?;
        }
        for v in &self.path {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let Some(ref v) = self.value.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.invert != false {
            os.write_bool(4, self.invert)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataMatcher {
        MetadataMatcher::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filter",
                |m: &MetadataMatcher| { &m.filter },
                |m: &mut MetadataMatcher| { &mut m.filter },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MetadataMatcher_PathSegment>>(
                "path",
                |m: &MetadataMatcher| { &m.path },
                |m: &mut MetadataMatcher| { &mut m.path },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::value::ValueMatcher>>(
                "value",
                |m: &MetadataMatcher| { &m.value },
                |m: &mut MetadataMatcher| { &mut m.value },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "invert",
                |m: &MetadataMatcher| { &m.invert },
                |m: &mut MetadataMatcher| { &mut m.invert },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataMatcher>(
                "MetadataMatcher",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataMatcher {
        static instance: ::protobuf::rt::LazyV2<MetadataMatcher> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataMatcher::new)
    }
}

impl ::protobuf::Clear for MetadataMatcher {
    fn clear(&mut self) {
        self.filter.clear();
        self.path.clear();
        self.value.clear();
        self.invert = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataMatcher {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataMatcher {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataMatcher_PathSegment {
    // message oneof groups
    pub segment: ::std::option::Option<MetadataMatcher_PathSegment_oneof_segment>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataMatcher_PathSegment {
    fn default() -> &'a MetadataMatcher_PathSegment {
        <MetadataMatcher_PathSegment as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum MetadataMatcher_PathSegment_oneof_segment {
    key(::std::string::String),
}

impl MetadataMatcher_PathSegment {
    pub fn new() -> MetadataMatcher_PathSegment {
        ::std::default::Default::default()
    }

    // string key = 1;


    pub fn get_key(&self) -> &str {
        match self.segment {
            ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_key(&mut self) {
        self.segment = ::std::option::Option::None;
    }

    pub fn has_key(&self) -> bool {
        match self.segment {
            ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.segment = ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(v))
    }

    // Mutable pointer to the field.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(_)) = self.segment {
        } else {
            self.segment = ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(::std::string::String::new()));
        }
        match self.segment {
            ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        if self.has_key() {
            match self.segment.take() {
                ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }
}

impl ::protobuf::Message for MetadataMatcher_PathSegment {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.segment = ::std::option::Option::Some(MetadataMatcher_PathSegment_oneof_segment::key(is.read_string()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.segment {
            match v {
                &MetadataMatcher_PathSegment_oneof_segment::key(ref v) => {
                    my_size += ::protobuf::rt::string_size(1, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.segment {
            match v {
                &MetadataMatcher_PathSegment_oneof_segment::key(ref v) => {
                    os.write_string(1, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataMatcher_PathSegment {
        MetadataMatcher_PathSegment::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "key",
                MetadataMatcher_PathSegment::has_key,
                MetadataMatcher_PathSegment::get_key,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataMatcher_PathSegment>(
                "MetadataMatcher.PathSegment",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataMatcher_PathSegment {
        static instance: ::protobuf::rt::LazyV2<MetadataMatcher_PathSegment> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataMatcher_PathSegment::new)
    }
}

impl ::protobuf::Clear for MetadataMatcher_PathSegment {
    fn clear(&mut self) {
        self.segment = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataMatcher_PathSegment {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataMatcher_PathSegment {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKey {
    // message fields
    pub key: ::std::string::String,
    pub path: ::protobuf::RepeatedField<MetadataKey_PathSegment>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKey {
    fn default() -> &'a MetadataKey {
        <MetadataKey as ::protobuf::Message>::default_instance()
    }
}

impl MetadataKey {
    pub fn new() -> MetadataKey {
        ::std::default::Default::default()
    }

    // string key = 1;


    pub fn get_key(&self) -> &str {
        &self.key
    }
    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.key, ::std::string::String::new())
    }

    // repeated .envoy.type.matcher.v3.MetadataKey.PathSegment path = 2;


    pub fn get_path(&self) -> &[MetadataKey_PathSegment] {
        &self.path
    }
    pub fn clear_path(&mut self) {
        self.path.clear();
    }

    // Param is passed by value, moved
    pub fn set_path(&mut self, v: ::protobuf::RepeatedField<MetadataKey_PathSegment>) {
        self.path = v;
    }

    // Mutable pointer to the field.
    pub fn mut_path(&mut self) -> &mut ::protobuf::RepeatedField<MetadataKey_PathSegment> {
        &mut self.path
    }

    // Take field
    pub fn take_path(&mut self) -> ::protobuf::RepeatedField<MetadataKey_PathSegment> {
        ::std::mem::replace(&mut self.path, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for MetadataKey {
    fn is_initialized(&self) -> bool {
        for v in &self.path {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.key)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.path)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.key);
        }
        for value in &self.path {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.key.is_empty() {
            os.write_string(1, &self.key)?;
        }
        for v in &self.path {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKey {
        MetadataKey::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "key",
                |m: &MetadataKey| { &m.key },
                |m: &mut MetadataKey| { &mut m.key },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MetadataKey_PathSegment>>(
                "path",
                |m: &MetadataKey| { &m.path },
                |m: &mut MetadataKey| { &mut m.path },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKey>(
                "MetadataKey",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKey {
        static instance: ::protobuf::rt::LazyV2<MetadataKey> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKey::new)
    }
}

impl ::protobuf::Clear for MetadataKey {
    fn clear(&mut self) {
        self.key.clear();
        self.path.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKey {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKey {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKey_PathSegment {
    // message oneof groups
    pub segment: ::std::option::Option<MetadataKey_PathSegment_oneof_segment>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKey_PathSegment {
    fn default() -> &'a MetadataKey_PathSegment {
        <MetadataKey_PathSegment as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum MetadataKey_PathSegment_oneof_segment {
    key(::std::string::String),
}

impl MetadataKey_PathSegment {
    pub fn new() -> MetadataKey_PathSegment {
        ::std::default::Default::default()
    }

    // string key = 1;


    pub fn get_key(&self) -> &str {
        match self.segment {
            ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_key(&mut self) {
        self.segment = ::std::option::Option::None;
    }

    pub fn has_key(&self) -> bool {
        match self.segment {
            ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.segment = ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(v))
    }

    // Mutable pointer to the field.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(_)) = self.segment {
        } else {
            self.segment = ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(::std::string::String::new()));
        }
        match self.segment {
            ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        if self.has_key() {
            match self.segment.take() {
                ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }
}

impl ::protobuf::Message for MetadataKey_PathSegment {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.segment = ::std::option::Option::Some(MetadataKey_PathSegment_oneof_segment::key(is.read_string()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.segment {
            match v {
                &MetadataKey_PathSegment_oneof_segment::key(ref v) => {
                    my_size += ::protobuf::rt::string_size(1, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.segment {
            match v {
                &MetadataKey_PathSegment_oneof_segment::key(ref v) => {
                    os.write_string(1, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKey_PathSegment {
        MetadataKey_PathSegment::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "key",
                MetadataKey_PathSegment::has_key,
                MetadataKey_PathSegment::get_key,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKey_PathSegment>(
                "MetadataKey.PathSegment",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKey_PathSegment {
        static instance: ::protobuf::rt::LazyV2<MetadataKey_PathSegment> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKey_PathSegment::new)
    }
}

impl ::protobuf::Clear for MetadataKey_PathSegment {
    fn clear(&mut self) {
        self.segment = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKey_PathSegment {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKey_PathSegment {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKind {
    // message oneof groups
    pub kind: ::std::option::Option<MetadataKind_oneof_kind>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKind {
    fn default() -> &'a MetadataKind {
        <MetadataKind as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum MetadataKind_oneof_kind {
    request(MetadataKind_Request),
    route(MetadataKind_Route),
    cluster(MetadataKind_Cluster),
    host(MetadataKind_Host),
}

impl MetadataKind {
    pub fn new() -> MetadataKind {
        ::std::default::Default::default()
    }

    // .envoy.type.matcher.v3.MetadataKind.Request request = 1;


    pub fn get_request(&self) -> &MetadataKind_Request {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::request(ref v)) => v,
            _ => <MetadataKind_Request as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_request(&mut self) {
        self.kind = ::std::option::Option::None;
    }

    pub fn has_request(&self) -> bool {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::request(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_request(&mut self, v: MetadataKind_Request) {
        self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::request(v))
    }

    // Mutable pointer to the field.
    pub fn mut_request(&mut self) -> &mut MetadataKind_Request {
        if let ::std::option::Option::Some(MetadataKind_oneof_kind::request(_)) = self.kind {
        } else {
            self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::request(MetadataKind_Request::new()));
        }
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::request(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_request(&mut self) -> MetadataKind_Request {
        if self.has_request() {
            match self.kind.take() {
                ::std::option::Option::Some(MetadataKind_oneof_kind::request(v)) => v,
                _ => panic!(),
            }
        } else {
            MetadataKind_Request::new()
        }
    }

    // .envoy.type.matcher.v3.MetadataKind.Route route = 2;


    pub fn get_route(&self) -> &MetadataKind_Route {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::route(ref v)) => v,
            _ => <MetadataKind_Route as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_route(&mut self) {
        self.kind = ::std::option::Option::None;
    }

    pub fn has_route(&self) -> bool {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::route(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_route(&mut self, v: MetadataKind_Route) {
        self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::route(v))
    }

    // Mutable pointer to the field.
    pub fn mut_route(&mut self) -> &mut MetadataKind_Route {
        if let ::std::option::Option::Some(MetadataKind_oneof_kind::route(_)) = self.kind {
        } else {
            self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::route(MetadataKind_Route::new()));
        }
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::route(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_route(&mut self) -> MetadataKind_Route {
        if self.has_route() {
            match self.kind.take() {
                ::std::option::Option::Some(MetadataKind_oneof_kind::route(v)) => v,
                _ => panic!(),
            }
        } else {
            MetadataKind_Route::new()
        }
    }

    // .envoy.type.matcher.v3.MetadataKind.Cluster cluster = 3;


    pub fn get_cluster(&self) -> &MetadataKind_Cluster {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(ref v)) => v,
            _ => <MetadataKind_Cluster as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_cluster(&mut self) {
        self.kind = ::std::option::Option::None;
    }

    pub fn has_cluster(&self) -> bool {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_cluster(&mut self, v: MetadataKind_Cluster) {
        self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(v))
    }

    // Mutable pointer to the field.
    pub fn mut_cluster(&mut self) -> &mut MetadataKind_Cluster {
        if let ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(_)) = self.kind {
        } else {
            self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(MetadataKind_Cluster::new()));
        }
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_cluster(&mut self) -> MetadataKind_Cluster {
        if self.has_cluster() {
            match self.kind.take() {
                ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(v)) => v,
                _ => panic!(),
            }
        } else {
            MetadataKind_Cluster::new()
        }
    }

    // .envoy.type.matcher.v3.MetadataKind.Host host = 4;


    pub fn get_host(&self) -> &MetadataKind_Host {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::host(ref v)) => v,
            _ => <MetadataKind_Host as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_host(&mut self) {
        self.kind = ::std::option::Option::None;
    }

    pub fn has_host(&self) -> bool {
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::host(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_host(&mut self, v: MetadataKind_Host) {
        self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::host(v))
    }

    // Mutable pointer to the field.
    pub fn mut_host(&mut self) -> &mut MetadataKind_Host {
        if let ::std::option::Option::Some(MetadataKind_oneof_kind::host(_)) = self.kind {
        } else {
            self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::host(MetadataKind_Host::new()));
        }
        match self.kind {
            ::std::option::Option::Some(MetadataKind_oneof_kind::host(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_host(&mut self) -> MetadataKind_Host {
        if self.has_host() {
            match self.kind.take() {
                ::std::option::Option::Some(MetadataKind_oneof_kind::host(v)) => v,
                _ => panic!(),
            }
        } else {
            MetadataKind_Host::new()
        }
    }
}

impl ::protobuf::Message for MetadataKind {
    fn is_initialized(&self) -> bool {
        if let Some(MetadataKind_oneof_kind::request(ref v)) = self.kind {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(MetadataKind_oneof_kind::route(ref v)) = self.kind {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(MetadataKind_oneof_kind::cluster(ref v)) = self.kind {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(MetadataKind_oneof_kind::host(ref v)) = self.kind {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::request(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::route(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::cluster(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.kind = ::std::option::Option::Some(MetadataKind_oneof_kind::host(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.kind {
            match v {
                &MetadataKind_oneof_kind::request(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &MetadataKind_oneof_kind::route(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &MetadataKind_oneof_kind::cluster(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &MetadataKind_oneof_kind::host(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.kind {
            match v {
                &MetadataKind_oneof_kind::request(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &MetadataKind_oneof_kind::route(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &MetadataKind_oneof_kind::cluster(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &MetadataKind_oneof_kind::host(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKind {
        MetadataKind::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, MetadataKind_Request>(
                "request",
                MetadataKind::has_request,
                MetadataKind::get_request,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, MetadataKind_Route>(
                "route",
                MetadataKind::has_route,
                MetadataKind::get_route,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, MetadataKind_Cluster>(
                "cluster",
                MetadataKind::has_cluster,
                MetadataKind::get_cluster,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, MetadataKind_Host>(
                "host",
                MetadataKind::has_host,
                MetadataKind::get_host,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKind>(
                "MetadataKind",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKind {
        static instance: ::protobuf::rt::LazyV2<MetadataKind> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKind::new)
    }
}

impl ::protobuf::Clear for MetadataKind {
    fn clear(&mut self) {
        self.kind = ::std::option::Option::None;
        self.kind = ::std::option::Option::None;
        self.kind = ::std::option::Option::None;
        self.kind = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKind {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKind_Request {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKind_Request {
    fn default() -> &'a MetadataKind_Request {
        <MetadataKind_Request as ::protobuf::Message>::default_instance()
    }
}

impl MetadataKind_Request {
    pub fn new() -> MetadataKind_Request {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MetadataKind_Request {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKind_Request {
        MetadataKind_Request::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKind_Request>(
                "MetadataKind.Request",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKind_Request {
        static instance: ::protobuf::rt::LazyV2<MetadataKind_Request> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKind_Request::new)
    }
}

impl ::protobuf::Clear for MetadataKind_Request {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKind_Request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKind_Request {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKind_Route {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKind_Route {
    fn default() -> &'a MetadataKind_Route {
        <MetadataKind_Route as ::protobuf::Message>::default_instance()
    }
}

impl MetadataKind_Route {
    pub fn new() -> MetadataKind_Route {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MetadataKind_Route {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKind_Route {
        MetadataKind_Route::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKind_Route>(
                "MetadataKind.Route",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKind_Route {
        static instance: ::protobuf::rt::LazyV2<MetadataKind_Route> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKind_Route::new)
    }
}

impl ::protobuf::Clear for MetadataKind_Route {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKind_Route {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKind_Route {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKind_Cluster {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKind_Cluster {
    fn default() -> &'a MetadataKind_Cluster {
        <MetadataKind_Cluster as ::protobuf::Message>::default_instance()
    }
}

impl MetadataKind_Cluster {
    pub fn new() -> MetadataKind_Cluster {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MetadataKind_Cluster {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKind_Cluster {
        MetadataKind_Cluster::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKind_Cluster>(
                "MetadataKind.Cluster",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKind_Cluster {
        static instance: ::protobuf::rt::LazyV2<MetadataKind_Cluster> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKind_Cluster::new)
    }
}

impl ::protobuf::Clear for MetadataKind_Cluster {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKind_Cluster {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKind_Cluster {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct MetadataKind_Host {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MetadataKind_Host {
    fn default() -> &'a MetadataKind_Host {
        <MetadataKind_Host as ::protobuf::Message>::default_instance()
    }
}

impl MetadataKind_Host {
    pub fn new() -> MetadataKind_Host {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MetadataKind_Host {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MetadataKind_Host {
        MetadataKind_Host::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MetadataKind_Host>(
                "MetadataKind.Host",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MetadataKind_Host {
        static instance: ::protobuf::rt::LazyV2<MetadataKind_Host> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MetadataKind_Host::new)
    }
}

impl ::protobuf::Clear for MetadataKind_Host {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MetadataKind_Host {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MetadataKind_Host {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$envoy/type/matcher/v3/metadata.proto\x12\x15envoy.type.matcher.v3\x1a\
    !envoy/type/matcher/v3/value.proto\x1a\x1dudpa/annotations/status.proto\
    \x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\
    \xff\x02\n\x0fMetadataMatcher\x12\x1f\n\x06filter\x18\x01\x20\x01(\tR\
    \x06filterB\x07\xfaB\x04r\x02\x10\x01\x12P\n\x04path\x18\x02\x20\x03(\
    \x0b22.envoy.type.matcher.v3.MetadataMatcher.PathSegmentR\x04pathB\x08\
    \xfaB\x05\x92\x01\x02\x08\x01\x12C\n\x05value\x18\x03\x20\x01(\x0b2#.env\
    oy.type.matcher.v3.ValueMatcherR\x05valueB\x08\xfaB\x05\x8a\x01\x02\x10\
    \x01\x12\x16\n\x06invert\x18\x04\x20\x01(\x08R\x06invert\x1aq\n\x0bPathS\
    egment\x12\x1b\n\x03key\x18\x01\x20\x01(\tH\0R\x03keyB\x07\xfaB\x04r\x02\
    \x10\x01B\x0e\n\x07segment\x12\x03\xf8B\x01:5\x9a\xc5\x88\x1e0\n.envoy.t\
    ype.matcher.MetadataMatcher.PathSegment:)\x9a\xc5\x88\x1e$\n\"envoy.type\
    .matcher.MetadataMatcher\"\x94\x02\n\x0bMetadataKey\x12\x19\n\x03key\x18\
    \x01\x20\x01(\tR\x03keyB\x07\xfaB\x04r\x02\x10\x01\x12L\n\x04path\x18\
    \x02\x20\x03(\x0b2..envoy.type.matcher.v3.MetadataKey.PathSegmentR\x04pa\
    thB\x08\xfaB\x05\x92\x01\x02\x08\x01\x1aq\n\x0bPathSegment\x12\x1b\n\x03\
    key\x18\x01\x20\x01(\tH\0R\x03keyB\x07\xfaB\x04r\x02\x10\x01B\x0e\n\x07s\
    egment\x12\x03\xf8B\x01:5\x9a\xc5\x88\x1e0\n.envoy.type.metadata.v2.Meta\
    dataKey.PathSegment:)\x9a\xc5\x88\x1e$\n\"envoy.type.metadata.v2.Metadat\
    aKey\"\xce\x04\n\x0cMetadataKind\x12G\n\x07request\x18\x01\x20\x01(\x0b2\
    +.envoy.type.matcher.v3.MetadataKind.RequestH\0R\x07request\x12A\n\x05ro\
    ute\x18\x02\x20\x01(\x0b2).envoy.type.matcher.v3.MetadataKind.RouteH\0R\
    \x05route\x12G\n\x07cluster\x18\x03\x20\x01(\x0b2+.envoy.type.matcher.v3\
    .MetadataKind.ClusterH\0R\x07cluster\x12>\n\x04host\x18\x04\x20\x01(\x0b\
    2(.envoy.type.matcher.v3.MetadataKind.HostH\0R\x04host\x1a=\n\x07Request\
    :2\x9a\xc5\x88\x1e-\n+envoy.type.metadata.v2.MetadataKind.Request\x1a9\n\
    \x05Route:0\x9a\xc5\x88\x1e+\n)envoy.type.metadata.v2.MetadataKind.Route\
    \x1a=\n\x07Cluster:2\x9a\xc5\x88\x1e-\n+envoy.type.metadata.v2.MetadataK\
    ind.Cluster\x1a7\n\x04Host:/\x9a\xc5\x88\x1e*\n(envoy.type.metadata.v2.M\
    etadataKind.HostB\x0b\n\x04kind\x12\x03\xf8B\x01:*\x9a\xc5\x88\x1e%\n#en\
    voy.type.metadata.v2.MetadataKindB>\n#io.envoyproxy.envoy.type.matcher.v\
    3B\rMetadataProtoP\x01\xba\x80\xc8\xd1\x06\x02\x10\x02b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
