// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `envoy/service/ratelimit/v3/rls.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RateLimitRequest {
    // message fields
    pub domain: ::std::string::String,
    pub descriptors: ::protobuf::RepeatedField<super::ratelimit::RateLimitDescriptor>,
    pub hits_addend: u32,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RateLimitRequest {
    fn default() -> &'a RateLimitRequest {
        <RateLimitRequest as ::protobuf::Message>::default_instance()
    }
}

impl RateLimitRequest {
    pub fn new() -> RateLimitRequest {
        ::std::default::Default::default()
    }

    // string domain = 1;


    pub fn get_domain(&self) -> &str {
        &self.domain
    }
    pub fn clear_domain(&mut self) {
        self.domain.clear();
    }

    // Param is passed by value, moved
    pub fn set_domain(&mut self, v: ::std::string::String) {
        self.domain = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_domain(&mut self) -> &mut ::std::string::String {
        &mut self.domain
    }

    // Take field
    pub fn take_domain(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.domain, ::std::string::String::new())
    }

    // repeated .envoy.extensions.common.ratelimit.v3.RateLimitDescriptor descriptors = 2;


    pub fn get_descriptors(&self) -> &[super::ratelimit::RateLimitDescriptor] {
        &self.descriptors
    }
    pub fn clear_descriptors(&mut self) {
        self.descriptors.clear();
    }

    // Param is passed by value, moved
    pub fn set_descriptors(&mut self, v: ::protobuf::RepeatedField<super::ratelimit::RateLimitDescriptor>) {
        self.descriptors = v;
    }

    // Mutable pointer to the field.
    pub fn mut_descriptors(&mut self) -> &mut ::protobuf::RepeatedField<super::ratelimit::RateLimitDescriptor> {
        &mut self.descriptors
    }

    // Take field
    pub fn take_descriptors(&mut self) -> ::protobuf::RepeatedField<super::ratelimit::RateLimitDescriptor> {
        ::std::mem::replace(&mut self.descriptors, ::protobuf::RepeatedField::new())
    }

    // uint32 hits_addend = 3;


    pub fn get_hits_addend(&self) -> u32 {
        self.hits_addend
    }
    pub fn clear_hits_addend(&mut self) {
        self.hits_addend = 0;
    }

    // Param is passed by value, moved
    pub fn set_hits_addend(&mut self, v: u32) {
        self.hits_addend = v;
    }
}

impl ::protobuf::Message for RateLimitRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.descriptors {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.domain)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.descriptors)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.hits_addend = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.domain.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.domain);
        }
        for value in &self.descriptors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.hits_addend != 0 {
            my_size += ::protobuf::rt::value_size(3, self.hits_addend, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.domain.is_empty() {
            os.write_string(1, &self.domain)?;
        }
        for v in &self.descriptors {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.hits_addend != 0 {
            os.write_uint32(3, self.hits_addend)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RateLimitRequest {
        RateLimitRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "domain",
                |m: &RateLimitRequest| { &m.domain },
                |m: &mut RateLimitRequest| { &mut m.domain },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::ratelimit::RateLimitDescriptor>>(
                "descriptors",
                |m: &RateLimitRequest| { &m.descriptors },
                |m: &mut RateLimitRequest| { &mut m.descriptors },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "hits_addend",
                |m: &RateLimitRequest| { &m.hits_addend },
                |m: &mut RateLimitRequest| { &mut m.hits_addend },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RateLimitRequest>(
                "RateLimitRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RateLimitRequest {
        static instance: ::protobuf::rt::LazyV2<RateLimitRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RateLimitRequest::new)
    }
}

impl ::protobuf::Clear for RateLimitRequest {
    fn clear(&mut self) {
        self.domain.clear();
        self.descriptors.clear();
        self.hits_addend = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RateLimitRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RateLimitResponse {
    // message fields
    pub overall_code: RateLimitResponse_Code,
    pub statuses: ::protobuf::RepeatedField<RateLimitResponse_DescriptorStatus>,
    pub response_headers_to_add: ::protobuf::RepeatedField<super::base::HeaderValue>,
    pub request_headers_to_add: ::protobuf::RepeatedField<super::base::HeaderValue>,
    pub raw_body: ::std::vec::Vec<u8>,
    pub dynamic_metadata: ::protobuf::SingularPtrField<::protobuf::well_known_types::Struct>,
    pub quota: ::protobuf::SingularPtrField<RateLimitResponse_Quota>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RateLimitResponse {
    fn default() -> &'a RateLimitResponse {
        <RateLimitResponse as ::protobuf::Message>::default_instance()
    }
}

impl RateLimitResponse {
    pub fn new() -> RateLimitResponse {
        ::std::default::Default::default()
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.Code overall_code = 1;


    pub fn get_overall_code(&self) -> RateLimitResponse_Code {
        self.overall_code
    }
    pub fn clear_overall_code(&mut self) {
        self.overall_code = RateLimitResponse_Code::UNKNOWN;
    }

    // Param is passed by value, moved
    pub fn set_overall_code(&mut self, v: RateLimitResponse_Code) {
        self.overall_code = v;
    }

    // repeated .envoy.service.ratelimit.v3.RateLimitResponse.DescriptorStatus statuses = 2;


    pub fn get_statuses(&self) -> &[RateLimitResponse_DescriptorStatus] {
        &self.statuses
    }
    pub fn clear_statuses(&mut self) {
        self.statuses.clear();
    }

    // Param is passed by value, moved
    pub fn set_statuses(&mut self, v: ::protobuf::RepeatedField<RateLimitResponse_DescriptorStatus>) {
        self.statuses = v;
    }

    // Mutable pointer to the field.
    pub fn mut_statuses(&mut self) -> &mut ::protobuf::RepeatedField<RateLimitResponse_DescriptorStatus> {
        &mut self.statuses
    }

    // Take field
    pub fn take_statuses(&mut self) -> ::protobuf::RepeatedField<RateLimitResponse_DescriptorStatus> {
        ::std::mem::replace(&mut self.statuses, ::protobuf::RepeatedField::new())
    }

    // repeated .envoy.config.core.v3.HeaderValue response_headers_to_add = 3;


    pub fn get_response_headers_to_add(&self) -> &[super::base::HeaderValue] {
        &self.response_headers_to_add
    }
    pub fn clear_response_headers_to_add(&mut self) {
        self.response_headers_to_add.clear();
    }

    // Param is passed by value, moved
    pub fn set_response_headers_to_add(&mut self, v: ::protobuf::RepeatedField<super::base::HeaderValue>) {
        self.response_headers_to_add = v;
    }

    // Mutable pointer to the field.
    pub fn mut_response_headers_to_add(&mut self) -> &mut ::protobuf::RepeatedField<super::base::HeaderValue> {
        &mut self.response_headers_to_add
    }

    // Take field
    pub fn take_response_headers_to_add(&mut self) -> ::protobuf::RepeatedField<super::base::HeaderValue> {
        ::std::mem::replace(&mut self.response_headers_to_add, ::protobuf::RepeatedField::new())
    }

    // repeated .envoy.config.core.v3.HeaderValue request_headers_to_add = 4;


    pub fn get_request_headers_to_add(&self) -> &[super::base::HeaderValue] {
        &self.request_headers_to_add
    }
    pub fn clear_request_headers_to_add(&mut self) {
        self.request_headers_to_add.clear();
    }

    // Param is passed by value, moved
    pub fn set_request_headers_to_add(&mut self, v: ::protobuf::RepeatedField<super::base::HeaderValue>) {
        self.request_headers_to_add = v;
    }

    // Mutable pointer to the field.
    pub fn mut_request_headers_to_add(&mut self) -> &mut ::protobuf::RepeatedField<super::base::HeaderValue> {
        &mut self.request_headers_to_add
    }

    // Take field
    pub fn take_request_headers_to_add(&mut self) -> ::protobuf::RepeatedField<super::base::HeaderValue> {
        ::std::mem::replace(&mut self.request_headers_to_add, ::protobuf::RepeatedField::new())
    }

    // bytes raw_body = 5;


    pub fn get_raw_body(&self) -> &[u8] {
        &self.raw_body
    }
    pub fn clear_raw_body(&mut self) {
        self.raw_body.clear();
    }

    // Param is passed by value, moved
    pub fn set_raw_body(&mut self, v: ::std::vec::Vec<u8>) {
        self.raw_body = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_raw_body(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.raw_body
    }

    // Take field
    pub fn take_raw_body(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.raw_body, ::std::vec::Vec::new())
    }

    // .google.protobuf.Struct dynamic_metadata = 6;


    pub fn get_dynamic_metadata(&self) -> &::protobuf::well_known_types::Struct {
        self.dynamic_metadata.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::Struct as ::protobuf::Message>::default_instance())
    }
    pub fn clear_dynamic_metadata(&mut self) {
        self.dynamic_metadata.clear();
    }

    pub fn has_dynamic_metadata(&self) -> bool {
        self.dynamic_metadata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_dynamic_metadata(&mut self, v: ::protobuf::well_known_types::Struct) {
        self.dynamic_metadata = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dynamic_metadata(&mut self) -> &mut ::protobuf::well_known_types::Struct {
        if self.dynamic_metadata.is_none() {
            self.dynamic_metadata.set_default();
        }
        self.dynamic_metadata.as_mut().unwrap()
    }

    // Take field
    pub fn take_dynamic_metadata(&mut self) -> ::protobuf::well_known_types::Struct {
        self.dynamic_metadata.take().unwrap_or_else(|| ::protobuf::well_known_types::Struct::new())
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.Quota quota = 7;


    pub fn get_quota(&self) -> &RateLimitResponse_Quota {
        self.quota.as_ref().unwrap_or_else(|| <RateLimitResponse_Quota as ::protobuf::Message>::default_instance())
    }
    pub fn clear_quota(&mut self) {
        self.quota.clear();
    }

    pub fn has_quota(&self) -> bool {
        self.quota.is_some()
    }

    // Param is passed by value, moved
    pub fn set_quota(&mut self, v: RateLimitResponse_Quota) {
        self.quota = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_quota(&mut self) -> &mut RateLimitResponse_Quota {
        if self.quota.is_none() {
            self.quota.set_default();
        }
        self.quota.as_mut().unwrap()
    }

    // Take field
    pub fn take_quota(&mut self) -> RateLimitResponse_Quota {
        self.quota.take().unwrap_or_else(|| RateLimitResponse_Quota::new())
    }
}

impl ::protobuf::Message for RateLimitResponse {
    fn is_initialized(&self) -> bool {
        for v in &self.statuses {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.response_headers_to_add {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.request_headers_to_add {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.dynamic_metadata {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.quota {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.overall_code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.statuses)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.response_headers_to_add)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.request_headers_to_add)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.raw_body)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.dynamic_metadata)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.quota)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.overall_code != RateLimitResponse_Code::UNKNOWN {
            my_size += ::protobuf::rt::enum_size(1, self.overall_code);
        }
        for value in &self.statuses {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.response_headers_to_add {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.request_headers_to_add {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if !self.raw_body.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.raw_body);
        }
        if let Some(ref v) = self.dynamic_metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.quota.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.overall_code != RateLimitResponse_Code::UNKNOWN {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.overall_code))?;
        }
        for v in &self.statuses {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.response_headers_to_add {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.request_headers_to_add {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if !self.raw_body.is_empty() {
            os.write_bytes(5, &self.raw_body)?;
        }
        if let Some(ref v) = self.dynamic_metadata.as_ref() {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.quota.as_ref() {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RateLimitResponse {
        RateLimitResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RateLimitResponse_Code>>(
                "overall_code",
                |m: &RateLimitResponse| { &m.overall_code },
                |m: &mut RateLimitResponse| { &mut m.overall_code },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RateLimitResponse_DescriptorStatus>>(
                "statuses",
                |m: &RateLimitResponse| { &m.statuses },
                |m: &mut RateLimitResponse| { &mut m.statuses },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::HeaderValue>>(
                "response_headers_to_add",
                |m: &RateLimitResponse| { &m.response_headers_to_add },
                |m: &mut RateLimitResponse| { &mut m.response_headers_to_add },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::HeaderValue>>(
                "request_headers_to_add",
                |m: &RateLimitResponse| { &m.request_headers_to_add },
                |m: &mut RateLimitResponse| { &mut m.request_headers_to_add },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "raw_body",
                |m: &RateLimitResponse| { &m.raw_body },
                |m: &mut RateLimitResponse| { &mut m.raw_body },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Struct>>(
                "dynamic_metadata",
                |m: &RateLimitResponse| { &m.dynamic_metadata },
                |m: &mut RateLimitResponse| { &mut m.dynamic_metadata },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RateLimitResponse_Quota>>(
                "quota",
                |m: &RateLimitResponse| { &m.quota },
                |m: &mut RateLimitResponse| { &mut m.quota },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RateLimitResponse>(
                "RateLimitResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RateLimitResponse {
        static instance: ::protobuf::rt::LazyV2<RateLimitResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RateLimitResponse::new)
    }
}

impl ::protobuf::Clear for RateLimitResponse {
    fn clear(&mut self) {
        self.overall_code = RateLimitResponse_Code::UNKNOWN;
        self.statuses.clear();
        self.response_headers_to_add.clear();
        self.request_headers_to_add.clear();
        self.raw_body.clear();
        self.dynamic_metadata.clear();
        self.quota.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RateLimitResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RateLimitResponse_RateLimit {
    // message fields
    pub name: ::std::string::String,
    pub requests_per_unit: u32,
    pub unit: RateLimitResponse_RateLimit_Unit,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RateLimitResponse_RateLimit {
    fn default() -> &'a RateLimitResponse_RateLimit {
        <RateLimitResponse_RateLimit as ::protobuf::Message>::default_instance()
    }
}

impl RateLimitResponse_RateLimit {
    pub fn new() -> RateLimitResponse_RateLimit {
        ::std::default::Default::default()
    }

    // string name = 3;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // uint32 requests_per_unit = 1;


    pub fn get_requests_per_unit(&self) -> u32 {
        self.requests_per_unit
    }
    pub fn clear_requests_per_unit(&mut self) {
        self.requests_per_unit = 0;
    }

    // Param is passed by value, moved
    pub fn set_requests_per_unit(&mut self, v: u32) {
        self.requests_per_unit = v;
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.RateLimit.Unit unit = 2;


    pub fn get_unit(&self) -> RateLimitResponse_RateLimit_Unit {
        self.unit
    }
    pub fn clear_unit(&mut self) {
        self.unit = RateLimitResponse_RateLimit_Unit::UNKNOWN;
    }

    // Param is passed by value, moved
    pub fn set_unit(&mut self, v: RateLimitResponse_RateLimit_Unit) {
        self.unit = v;
    }
}

impl ::protobuf::Message for RateLimitResponse_RateLimit {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.requests_per_unit = tmp;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.unit, 2, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.name);
        }
        if self.requests_per_unit != 0 {
            my_size += ::protobuf::rt::value_size(1, self.requests_per_unit, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.unit != RateLimitResponse_RateLimit_Unit::UNKNOWN {
            my_size += ::protobuf::rt::enum_size(2, self.unit);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(3, &self.name)?;
        }
        if self.requests_per_unit != 0 {
            os.write_uint32(1, self.requests_per_unit)?;
        }
        if self.unit != RateLimitResponse_RateLimit_Unit::UNKNOWN {
            os.write_enum(2, ::protobuf::ProtobufEnum::value(&self.unit))?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RateLimitResponse_RateLimit {
        RateLimitResponse_RateLimit::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &RateLimitResponse_RateLimit| { &m.name },
                |m: &mut RateLimitResponse_RateLimit| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "requests_per_unit",
                |m: &RateLimitResponse_RateLimit| { &m.requests_per_unit },
                |m: &mut RateLimitResponse_RateLimit| { &mut m.requests_per_unit },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RateLimitResponse_RateLimit_Unit>>(
                "unit",
                |m: &RateLimitResponse_RateLimit| { &m.unit },
                |m: &mut RateLimitResponse_RateLimit| { &mut m.unit },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RateLimitResponse_RateLimit>(
                "RateLimitResponse.RateLimit",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RateLimitResponse_RateLimit {
        static instance: ::protobuf::rt::LazyV2<RateLimitResponse_RateLimit> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RateLimitResponse_RateLimit::new)
    }
}

impl ::protobuf::Clear for RateLimitResponse_RateLimit {
    fn clear(&mut self) {
        self.name.clear();
        self.requests_per_unit = 0;
        self.unit = RateLimitResponse_RateLimit_Unit::UNKNOWN;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RateLimitResponse_RateLimit {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse_RateLimit {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum RateLimitResponse_RateLimit_Unit {
    UNKNOWN = 0,
    SECOND = 1,
    MINUTE = 2,
    HOUR = 3,
    DAY = 4,
}

impl ::protobuf::ProtobufEnum for RateLimitResponse_RateLimit_Unit {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RateLimitResponse_RateLimit_Unit> {
        match value {
            0 => ::std::option::Option::Some(RateLimitResponse_RateLimit_Unit::UNKNOWN),
            1 => ::std::option::Option::Some(RateLimitResponse_RateLimit_Unit::SECOND),
            2 => ::std::option::Option::Some(RateLimitResponse_RateLimit_Unit::MINUTE),
            3 => ::std::option::Option::Some(RateLimitResponse_RateLimit_Unit::HOUR),
            4 => ::std::option::Option::Some(RateLimitResponse_RateLimit_Unit::DAY),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [RateLimitResponse_RateLimit_Unit] = &[
            RateLimitResponse_RateLimit_Unit::UNKNOWN,
            RateLimitResponse_RateLimit_Unit::SECOND,
            RateLimitResponse_RateLimit_Unit::MINUTE,
            RateLimitResponse_RateLimit_Unit::HOUR,
            RateLimitResponse_RateLimit_Unit::DAY,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<RateLimitResponse_RateLimit_Unit>("RateLimitResponse.RateLimit.Unit", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for RateLimitResponse_RateLimit_Unit {
}

impl ::std::default::Default for RateLimitResponse_RateLimit_Unit {
    fn default() -> Self {
        RateLimitResponse_RateLimit_Unit::UNKNOWN
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse_RateLimit_Unit {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RateLimitResponse_Quota {
    // message fields
    pub requests: u32,
    pub id: ::std::string::String,
    // message oneof groups
    pub expiration_specifier: ::std::option::Option<RateLimitResponse_Quota_oneof_expiration_specifier>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RateLimitResponse_Quota {
    fn default() -> &'a RateLimitResponse_Quota {
        <RateLimitResponse_Quota as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum RateLimitResponse_Quota_oneof_expiration_specifier {
    valid_until(::protobuf::well_known_types::Timestamp),
}

impl RateLimitResponse_Quota {
    pub fn new() -> RateLimitResponse_Quota {
        ::std::default::Default::default()
    }

    // uint32 requests = 1;


    pub fn get_requests(&self) -> u32 {
        self.requests
    }
    pub fn clear_requests(&mut self) {
        self.requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_requests(&mut self, v: u32) {
        self.requests = v;
    }

    // .google.protobuf.Timestamp valid_until = 2;


    pub fn get_valid_until(&self) -> &::protobuf::well_known_types::Timestamp {
        match self.expiration_specifier {
            ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(ref v)) => v,
            _ => <::protobuf::well_known_types::Timestamp as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_valid_until(&mut self) {
        self.expiration_specifier = ::std::option::Option::None;
    }

    pub fn has_valid_until(&self) -> bool {
        match self.expiration_specifier {
            ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_valid_until(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.expiration_specifier = ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(v))
    }

    // Mutable pointer to the field.
    pub fn mut_valid_until(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if let ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(_)) = self.expiration_specifier {
        } else {
            self.expiration_specifier = ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(::protobuf::well_known_types::Timestamp::new()));
        }
        match self.expiration_specifier {
            ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_valid_until(&mut self) -> ::protobuf::well_known_types::Timestamp {
        if self.has_valid_until() {
            match self.expiration_specifier.take() {
                ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(v)) => v,
                _ => panic!(),
            }
        } else {
            ::protobuf::well_known_types::Timestamp::new()
        }
    }

    // string id = 3;


    pub fn get_id(&self) -> &str {
        &self.id
    }
    pub fn clear_id(&mut self) {
        self.id.clear();
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: ::std::string::String) {
        self.id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_id(&mut self) -> &mut ::std::string::String {
        &mut self.id
    }

    // Take field
    pub fn take_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.id, ::std::string::String::new())
    }
}

impl ::protobuf::Message for RateLimitResponse_Quota {
    fn is_initialized(&self) -> bool {
        if let Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(ref v)) = self.expiration_specifier {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.requests = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.expiration_specifier = ::std::option::Option::Some(RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(is.read_message()?));
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.id)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.requests != 0 {
            my_size += ::protobuf::rt::value_size(1, self.requests, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.id);
        }
        if let ::std::option::Option::Some(ref v) = self.expiration_specifier {
            match v {
                &RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.requests != 0 {
            os.write_uint32(1, self.requests)?;
        }
        if !self.id.is_empty() {
            os.write_string(3, &self.id)?;
        }
        if let ::std::option::Option::Some(ref v) = self.expiration_specifier {
            match v {
                &RateLimitResponse_Quota_oneof_expiration_specifier::valid_until(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RateLimitResponse_Quota {
        RateLimitResponse_Quota::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "requests",
                |m: &RateLimitResponse_Quota| { &m.requests },
                |m: &mut RateLimitResponse_Quota| { &mut m.requests },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ::protobuf::well_known_types::Timestamp>(
                "valid_until",
                RateLimitResponse_Quota::has_valid_until,
                RateLimitResponse_Quota::get_valid_until,
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "id",
                |m: &RateLimitResponse_Quota| { &m.id },
                |m: &mut RateLimitResponse_Quota| { &mut m.id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RateLimitResponse_Quota>(
                "RateLimitResponse.Quota",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RateLimitResponse_Quota {
        static instance: ::protobuf::rt::LazyV2<RateLimitResponse_Quota> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RateLimitResponse_Quota::new)
    }
}

impl ::protobuf::Clear for RateLimitResponse_Quota {
    fn clear(&mut self) {
        self.requests = 0;
        self.expiration_specifier = ::std::option::Option::None;
        self.id.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RateLimitResponse_Quota {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse_Quota {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RateLimitResponse_DescriptorStatus {
    // message fields
    pub code: RateLimitResponse_Code,
    pub current_limit: ::protobuf::SingularPtrField<RateLimitResponse_RateLimit>,
    pub limit_remaining: u32,
    pub duration_until_reset: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    pub quota: ::protobuf::SingularPtrField<RateLimitResponse_Quota>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RateLimitResponse_DescriptorStatus {
    fn default() -> &'a RateLimitResponse_DescriptorStatus {
        <RateLimitResponse_DescriptorStatus as ::protobuf::Message>::default_instance()
    }
}

impl RateLimitResponse_DescriptorStatus {
    pub fn new() -> RateLimitResponse_DescriptorStatus {
        ::std::default::Default::default()
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.Code code = 1;


    pub fn get_code(&self) -> RateLimitResponse_Code {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = RateLimitResponse_Code::UNKNOWN;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: RateLimitResponse_Code) {
        self.code = v;
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.RateLimit current_limit = 2;


    pub fn get_current_limit(&self) -> &RateLimitResponse_RateLimit {
        self.current_limit.as_ref().unwrap_or_else(|| <RateLimitResponse_RateLimit as ::protobuf::Message>::default_instance())
    }
    pub fn clear_current_limit(&mut self) {
        self.current_limit.clear();
    }

    pub fn has_current_limit(&self) -> bool {
        self.current_limit.is_some()
    }

    // Param is passed by value, moved
    pub fn set_current_limit(&mut self, v: RateLimitResponse_RateLimit) {
        self.current_limit = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_current_limit(&mut self) -> &mut RateLimitResponse_RateLimit {
        if self.current_limit.is_none() {
            self.current_limit.set_default();
        }
        self.current_limit.as_mut().unwrap()
    }

    // Take field
    pub fn take_current_limit(&mut self) -> RateLimitResponse_RateLimit {
        self.current_limit.take().unwrap_or_else(|| RateLimitResponse_RateLimit::new())
    }

    // uint32 limit_remaining = 3;


    pub fn get_limit_remaining(&self) -> u32 {
        self.limit_remaining
    }
    pub fn clear_limit_remaining(&mut self) {
        self.limit_remaining = 0;
    }

    // Param is passed by value, moved
    pub fn set_limit_remaining(&mut self, v: u32) {
        self.limit_remaining = v;
    }

    // .google.protobuf.Duration duration_until_reset = 4;


    pub fn get_duration_until_reset(&self) -> &::protobuf::well_known_types::Duration {
        self.duration_until_reset.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::Duration as ::protobuf::Message>::default_instance())
    }
    pub fn clear_duration_until_reset(&mut self) {
        self.duration_until_reset.clear();
    }

    pub fn has_duration_until_reset(&self) -> bool {
        self.duration_until_reset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_duration_until_reset(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.duration_until_reset = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_duration_until_reset(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.duration_until_reset.is_none() {
            self.duration_until_reset.set_default();
        }
        self.duration_until_reset.as_mut().unwrap()
    }

    // Take field
    pub fn take_duration_until_reset(&mut self) -> ::protobuf::well_known_types::Duration {
        self.duration_until_reset.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }

    // .envoy.service.ratelimit.v3.RateLimitResponse.Quota quota = 5;


    pub fn get_quota(&self) -> &RateLimitResponse_Quota {
        self.quota.as_ref().unwrap_or_else(|| <RateLimitResponse_Quota as ::protobuf::Message>::default_instance())
    }
    pub fn clear_quota(&mut self) {
        self.quota.clear();
    }

    pub fn has_quota(&self) -> bool {
        self.quota.is_some()
    }

    // Param is passed by value, moved
    pub fn set_quota(&mut self, v: RateLimitResponse_Quota) {
        self.quota = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_quota(&mut self) -> &mut RateLimitResponse_Quota {
        if self.quota.is_none() {
            self.quota.set_default();
        }
        self.quota.as_mut().unwrap()
    }

    // Take field
    pub fn take_quota(&mut self) -> RateLimitResponse_Quota {
        self.quota.take().unwrap_or_else(|| RateLimitResponse_Quota::new())
    }
}

impl ::protobuf::Message for RateLimitResponse_DescriptorStatus {
    fn is_initialized(&self) -> bool {
        for v in &self.current_limit {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.duration_until_reset {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.quota {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.current_limit)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.limit_remaining = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.duration_until_reset)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.quota)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != RateLimitResponse_Code::UNKNOWN {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if let Some(ref v) = self.current_limit.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.limit_remaining != 0 {
            my_size += ::protobuf::rt::value_size(3, self.limit_remaining, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.duration_until_reset.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.quota.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.code != RateLimitResponse_Code::UNKNOWN {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.code))?;
        }
        if let Some(ref v) = self.current_limit.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.limit_remaining != 0 {
            os.write_uint32(3, self.limit_remaining)?;
        }
        if let Some(ref v) = self.duration_until_reset.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.quota.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RateLimitResponse_DescriptorStatus {
        RateLimitResponse_DescriptorStatus::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RateLimitResponse_Code>>(
                "code",
                |m: &RateLimitResponse_DescriptorStatus| { &m.code },
                |m: &mut RateLimitResponse_DescriptorStatus| { &mut m.code },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RateLimitResponse_RateLimit>>(
                "current_limit",
                |m: &RateLimitResponse_DescriptorStatus| { &m.current_limit },
                |m: &mut RateLimitResponse_DescriptorStatus| { &mut m.current_limit },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "limit_remaining",
                |m: &RateLimitResponse_DescriptorStatus| { &m.limit_remaining },
                |m: &mut RateLimitResponse_DescriptorStatus| { &mut m.limit_remaining },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                "duration_until_reset",
                |m: &RateLimitResponse_DescriptorStatus| { &m.duration_until_reset },
                |m: &mut RateLimitResponse_DescriptorStatus| { &mut m.duration_until_reset },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RateLimitResponse_Quota>>(
                "quota",
                |m: &RateLimitResponse_DescriptorStatus| { &m.quota },
                |m: &mut RateLimitResponse_DescriptorStatus| { &mut m.quota },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RateLimitResponse_DescriptorStatus>(
                "RateLimitResponse.DescriptorStatus",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RateLimitResponse_DescriptorStatus {
        static instance: ::protobuf::rt::LazyV2<RateLimitResponse_DescriptorStatus> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RateLimitResponse_DescriptorStatus::new)
    }
}

impl ::protobuf::Clear for RateLimitResponse_DescriptorStatus {
    fn clear(&mut self) {
        self.code = RateLimitResponse_Code::UNKNOWN;
        self.current_limit.clear();
        self.limit_remaining = 0;
        self.duration_until_reset.clear();
        self.quota.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RateLimitResponse_DescriptorStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse_DescriptorStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum RateLimitResponse_Code {
    UNKNOWN = 0,
    OK = 1,
    OVER_LIMIT = 2,
}

impl ::protobuf::ProtobufEnum for RateLimitResponse_Code {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RateLimitResponse_Code> {
        match value {
            0 => ::std::option::Option::Some(RateLimitResponse_Code::UNKNOWN),
            1 => ::std::option::Option::Some(RateLimitResponse_Code::OK),
            2 => ::std::option::Option::Some(RateLimitResponse_Code::OVER_LIMIT),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [RateLimitResponse_Code] = &[
            RateLimitResponse_Code::UNKNOWN,
            RateLimitResponse_Code::OK,
            RateLimitResponse_Code::OVER_LIMIT,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<RateLimitResponse_Code>("RateLimitResponse.Code", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for RateLimitResponse_Code {
}

impl ::std::default::Default for RateLimitResponse_Code {
    fn default() -> Self {
        RateLimitResponse_Code::UNKNOWN
    }
}

impl ::protobuf::reflect::ProtobufValue for RateLimitResponse_Code {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$envoy/service/ratelimit/v3/rls.proto\x12\x1aenvoy.service.ratelimit.v\
    3\x1a\x1fenvoy/config/core/v3/base.proto\x1a4envoy/extensions/common/rat\
    elimit/v3/ratelimit.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cg\
    oogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\
    \x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\
    \x1a\x17validate/validate.proto\"\xdc\x01\n\x10RateLimitRequest\x12\x16\
    \n\x06domain\x18\x01\x20\x01(\tR\x06domain\x12[\n\x0bdescriptors\x18\x02\
    \x20\x03(\x0b29.envoy.extensions.common.ratelimit.v3.RateLimitDescriptor\
    R\x0bdescriptors\x12\x1f\n\x0bhits_addend\x18\x03\x20\x01(\rR\nhitsAdden\
    d:2\x9a\xc5\x88\x1e-\n+envoy.service.ratelimit.v2.RateLimitRequest\"\xfb\
    \x0b\n\x11RateLimitResponse\x12U\n\x0coverall_code\x18\x01\x20\x01(\x0e2\
    2.envoy.service.ratelimit.v3.RateLimitResponse.CodeR\x0boverallCode\x12Z\
    \n\x08statuses\x18\x02\x20\x03(\x0b2>.envoy.service.ratelimit.v3.RateLim\
    itResponse.DescriptorStatusR\x08statuses\x12X\n\x17response_headers_to_a\
    dd\x18\x03\x20\x03(\x0b2!.envoy.config.core.v3.HeaderValueR\x14responseH\
    eadersToAdd\x12V\n\x16request_headers_to_add\x18\x04\x20\x03(\x0b2!.envo\
    y.config.core.v3.HeaderValueR\x13requestHeadersToAdd\x12\x19\n\x08raw_bo\
    dy\x18\x05\x20\x01(\x0cR\x07rawBody\x12B\n\x10dynamic_metadata\x18\x06\
    \x20\x01(\x0b2\x17.google.protobuf.StructR\x0fdynamicMetadata\x12I\n\x05\
    quota\x18\x07\x20\x01(\x0b23.envoy.service.ratelimit.v3.RateLimitRespons\
    e.QuotaR\x05quota\x1a\x9c\x02\n\tRateLimit\x12\x12\n\x04name\x18\x03\x20\
    \x01(\tR\x04name\x12*\n\x11requests_per_unit\x18\x01\x20\x01(\rR\x0frequ\
    estsPerUnit\x12P\n\x04unit\x18\x02\x20\x01(\x0e2<.envoy.service.ratelimi\
    t.v3.RateLimitResponse.RateLimit.UnitR\x04unit\">\n\x04Unit\x12\x0b\n\
    \x07UNKNOWN\x10\0\x12\n\n\x06SECOND\x10\x01\x12\n\n\x06MINUTE\x10\x02\
    \x12\x08\n\x04HOUR\x10\x03\x12\x07\n\x03DAY\x10\x04:=\x9a\xc5\x88\x1e8\n\
    6envoy.service.ratelimit.v2.RateLimitResponse.RateLimit\x1a\x93\x01\n\
    \x05Quota\x12#\n\x08requests\x18\x01\x20\x01(\rR\x08requestsB\x07\xfaB\
    \x04*\x02\x20\0\x12=\n\x0bvalid_until\x18\x02\x20\x01(\x0b2\x1a.google.p\
    rotobuf.TimestampH\0R\nvalidUntil\x12\x0e\n\x02id\x18\x03\x20\x01(\tR\
    \x02idB\x16\n\x14expiration_specifier\x1a\xbf\x03\n\x10DescriptorStatus\
    \x12F\n\x04code\x18\x01\x20\x01(\x0e22.envoy.service.ratelimit.v3.RateLi\
    mitResponse.CodeR\x04code\x12\\\n\rcurrent_limit\x18\x02\x20\x01(\x0b27.\
    envoy.service.ratelimit.v3.RateLimitResponse.RateLimitR\x0ccurrentLimit\
    \x12'\n\x0flimit_remaining\x18\x03\x20\x01(\rR\x0elimitRemaining\x12K\n\
    \x14duration_until_reset\x18\x04\x20\x01(\x0b2\x19.google.protobuf.Durat\
    ionR\x12durationUntilReset\x12I\n\x05quota\x18\x05\x20\x01(\x0b23.envoy.\
    service.ratelimit.v3.RateLimitResponse.QuotaR\x05quota:D\x9a\xc5\x88\x1e\
    ?\n=envoy.service.ratelimit.v2.RateLimitResponse.DescriptorStatus\"+\n\
    \x04Code\x12\x0b\n\x07UNKNOWN\x10\0\x12\x06\n\x02OK\x10\x01\x12\x0e\n\nO\
    VER_LIMIT\x10\x02:3\x9a\xc5\x88\x1e.\n,envoy.service.ratelimit.v2.RateLi\
    mitResponse2\x84\x01\n\x10RateLimitService\x12p\n\x0fShouldRateLimit\x12\
    ,.envoy.service.ratelimit.v3.RateLimitRequest\x1a-.envoy.service.ratelim\
    it.v3.RateLimitResponse\"\0BA\n(io.envoyproxy.envoy.service.ratelimit.v3\
    B\x08RlsProtoP\x01\x88\x01\x01\xba\x80\xc8\xd1\x06\x02\x10\x02b\x06proto\
    3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
