# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
---
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixing 🐞
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
