[package]
name = "wasm-shim"
version = "0.4.0"
edition = "2021"
authors = ["Rahul Anand <rahulanand16nov@gmail.com>"]
description = "shim connecting envoy and authorino/limitador"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["with-serde"]
with-serde = ["protobuf/with-serde"]

[dependencies]
proxy-wasm = "0.2.1"
serde_json = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
prost = "0.11"
prost-types = "0.11"
protobuf = { version = "2.27", features = ["with-serde"] }
thiserror = "1.0"
regex = "1"
radix_trie = "0.2.1"

[dev-dependencies]
proxy-wasm-test-framework = { git = "https://github.com/Kuadrant/wasm-test-framework.git", branch = "kuadrant" }
serial_test = "2.0.0"

[build-dependencies]
protoc-rust = "2.27"
