---
version: '2.2'
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    depends_on:
      - limitador
      - upstream
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - wasm:debug,http:debug,router:debug
      - --service-cluster
      - proxy
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
    volumes:
      - ./utils/docker-compose/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/wasm_shim.wasm:/opt/kuadrant/wasm/wasm_shim.wasm
  limitador:
    image: quay.io/kuadrant/limitador:latest
    command: ["limitador-server", "-vvv", "/opt/kuadrant/limits/limits.yaml"]
    expose:
      - "8080"
      - "8081"
    volumes:
      - ./utils/docker-compose/limits.yaml:/opt/kuadrant/limits/limits.yaml
  upstream:
    image: kennethreitz/httpbin
