---
- namespace: rls-domain-b
  max_value: 5
  seconds: 10
  conditions:
    - "some_generic_key == 'some_generic_value'"
  variables: []
- namespace: rls-domain-c
  max_value: 2
  seconds: 10
  conditions: ["user_id == 'bob'"]
  variables: []
