---
- namespace: toystore-app
  max_value: 10
  seconds: 60
  conditions:
    - "req.method == GET"
  variables: []
- namespace: rls-domain-c
  max_value: 2
  seconds: 10
  conditions: ["user-id == bob"]
  variables: []