---
services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    depends_on:
    - rlsbin
    - upstream
    command:
    - /usr/local/bin/envoy
    - --config-path
    - /etc/envoy.yaml
    - --log-level
    - info
    - --component-log-level
    - wasm:debug,http:debug,router:debug
    - --service-cluster
    - proxy
    expose:
    - "80"
    - "8001"
    ports:
    - "18000:80"
    - "18001:8001"
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
    - ../../target/wasm32-unknown-unknown/debug/wasm_shim.wasm:/opt/kuadrant/wasm/wasm_shim.wasm
  rlsbin:
    image: quay.io/eastizle/rlsbin:v0.1.0
    command:
    - rlsbin
    - -vvv
    ports:
    - "18081:8081"
    expose:
    - "8081"
  upstream:
    image: quay.io/kuadrant/authorino-examples:talker-api
    environment:
      PORT: 3000
      LOG_LEVEL: debug
    expose:
    - "3000"
  start_services:
    image: alpine
    depends_on:
    - envoy
    command: >
      /bin/sh -c "
      while ! nc -z envoy 80;
      do
      echo sleeping;
      sleep 1;
      done;
      echo Connected!
      "
