 apiVersion: extensions.istio.io/v1alpha1
 kind: WasmPlugin
 metadata:
   name: demo
   namespace: istio-system
 spec:
    selector:
      matchLabels:
        app: toystore
    url: https://raw.githubusercontent.com/Kuadrant/wasm-shim/main/deploy/wasm_shim.wasm
    pluginConfig:
      operations:
        - Authenticate:
            upstream_cluster: "outbound|50051||authorino-authorino-authorization.default.svc.cluster.local"
      failure_mode_deny: true
