// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `envoy/config/core/v3/backoff.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct BackoffStrategy {
    // message fields
    pub base_interval: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    pub max_interval: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BackoffStrategy {
    fn default() -> &'a BackoffStrategy {
        <BackoffStrategy as ::protobuf::Message>::default_instance()
    }
}

impl BackoffStrategy {
    pub fn new() -> BackoffStrategy {
        ::std::default::Default::default()
    }

    // .google.protobuf.Duration base_interval = 1;


    pub fn get_base_interval(&self) -> &::protobuf::well_known_types::Duration {
        self.base_interval.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::Duration as ::protobuf::Message>::default_instance())
    }
    pub fn clear_base_interval(&mut self) {
        self.base_interval.clear();
    }

    pub fn has_base_interval(&self) -> bool {
        self.base_interval.is_some()
    }

    // Param is passed by value, moved
    pub fn set_base_interval(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.base_interval = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_base_interval(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.base_interval.is_none() {
            self.base_interval.set_default();
        }
        self.base_interval.as_mut().unwrap()
    }

    // Take field
    pub fn take_base_interval(&mut self) -> ::protobuf::well_known_types::Duration {
        self.base_interval.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }

    // .google.protobuf.Duration max_interval = 2;


    pub fn get_max_interval(&self) -> &::protobuf::well_known_types::Duration {
        self.max_interval.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::Duration as ::protobuf::Message>::default_instance())
    }
    pub fn clear_max_interval(&mut self) {
        self.max_interval.clear();
    }

    pub fn has_max_interval(&self) -> bool {
        self.max_interval.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_interval(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.max_interval = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_max_interval(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.max_interval.is_none() {
            self.max_interval.set_default();
        }
        self.max_interval.as_mut().unwrap()
    }

    // Take field
    pub fn take_max_interval(&mut self) -> ::protobuf::well_known_types::Duration {
        self.max_interval.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }
}

impl ::protobuf::Message for BackoffStrategy {
    fn is_initialized(&self) -> bool {
        for v in &self.base_interval {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.max_interval {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.base_interval)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.max_interval)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.base_interval.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.max_interval.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.base_interval.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.max_interval.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BackoffStrategy {
        BackoffStrategy::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                "base_interval",
                |m: &BackoffStrategy| { &m.base_interval },
                |m: &mut BackoffStrategy| { &mut m.base_interval },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                "max_interval",
                |m: &BackoffStrategy| { &m.max_interval },
                |m: &mut BackoffStrategy| { &mut m.max_interval },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BackoffStrategy>(
                "BackoffStrategy",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BackoffStrategy {
        static instance: ::protobuf::rt::LazyV2<BackoffStrategy> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BackoffStrategy::new)
    }
}

impl ::protobuf::Clear for BackoffStrategy {
    fn clear(&mut self) {
        self.base_interval.clear();
        self.max_interval.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BackoffStrategy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BackoffStrategy {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\"envoy/config/core/v3/backoff.proto\x12\x14envoy.config.core.v3\x1a\
    \x1egoogle/protobuf/duration.proto\x1a\x1dudpa/annotations/status.proto\
    \x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\
    \xd3\x01\n\x0fBackoffStrategy\x12N\n\rbase_interval\x18\x01\x20\x01(\x0b\
    2\x19.google.protobuf.DurationR\x0cbaseIntervalB\x0e\xfaB\x0b\xaa\x01\
    \x08\x08\x012\x04\x10\xc0\x84=\x12F\n\x0cmax_interval\x18\x02\x20\x01(\
    \x0b2\x19.google.protobuf.DurationR\x0bmaxIntervalB\x08\xfaB\x05\xaa\x01\
    \x02*\0:(\x9a\xc5\x88\x1e#\n!envoy.api.v2.core.BackoffStrategyB<\n\"io.e\
    nvoyproxy.envoy.config.core.v3B\x0cBackoffProtoP\x01\xba\x80\xc8\xd1\x06\
    \x02\x10\x02b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
