name: Automated Release WASM Shim

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Commit SHA, tag or branch name (usually main branch)
        required: true
        default: "main"
        type: string
      wasmShimVersion:
        description: WASM Shim version (semver, e.g., 0.12.1)
        required: true
        default: "0.0.0"
        type: string

jobs:
  auto-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at git ref
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.gitRef }}
          token: ${{ secrets.KUADRANT_DEV_PAT }}

      - name: Prepare release
        uses: ./.github/actions/prepare-release
        with:
          version: ${{ github.event.inputs.wasmShimVersion }}
          push-branch: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.KUADRANT_DEV_PAT }}
          commit-message: Prepare release ${{ github.event.inputs.wasmShimVersion }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          base: ${{ env.BASE_BRANCH }}
          branch: release-${{ env.WASM_SHIM_VERSION }}
          delete-branch: true
          title: "[Release] WASM Shim v${{ env.WASM_SHIM_VERSION }}"
          body: |
            Prepare release for WASM Shim version ${{ env.WASM_SHIM_VERSION }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
